# Codecov Configuration

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        base: auto
    patch:
      default:
        target: 80%
        threshold: 1%
    changes:
      default:
        target: 80%
        threshold: 1%

  flags:
    backend:
      paths:
        - backend/
      target: 80%
    frontend:
      paths:
        - frontend/
      target: 80%

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

github_checks:
  annotations: true

ignore:
  - "backend/tests/"
  - "frontend/src/test/"
  - "frontend/src/**/*.test.ts"
  - "frontend/src/**/*.test.tsx"
  - "**/*.d.ts"
  - "**/node_modules/"
  - "**/__pycache__/"
  - "**/.pytest_cache/"
  - "**/coverage/"
  - "**/dist/"
  - "**/build/"